### ISSUE TITLE
8. Add Links to Register

### ISSUE THREAD

**Issue by TylerSandman** [hsha0/CodeU-Spring2018-Team19#11]
See here: https://sites.google.com/codeustudents.com/main/projects/project-1-adding-a-registration-page/8-add-links-to-register

**Comment by CalamariDude** [comment]
Hey I added this, should I close the issue?

**Comment by TylerSandman** [comment]
SGTM. Just comment with the commit hash for bookkeeping

**Comment by CalamariDude** [comment]
Yes,
#️⃣ e2d5c4d02ad310762e4bec5a7ff3923e9a151484
#18
