### ISSUE TITLE
6. Modify login.jsp to take a username and a password.

### ISSUE THREAD

**Issue by trishazalani** [hsha0/CodeU-Spring2018-Team19#8]
See here: https://sites.google.com/codeustudents.com/main/projects/project-1-adding-a-registration-page/6-modify-login-jsp

**Comment by TylerSandman** [comment]
Fixed with commit [e91af54c6d0a6fba24bcdda0a3ed928663bbb3e4](https://github.com/hsha0/CodeU-Spring2018-Team19/commit/e91af54c6d0a6fba24bcdda0a3ed928663bbb3e4)
